[Radarr-1080p]
Managed = true
URI = "CHANGE_ME"
APIKey = "CHANGE_ME"
ReSearch = true
importMode = "Move"
RssSyncTimer = 10
RefreshDownloadsTimer = 1
category = "radarr-1080"

[Radarr-4k]
Managed = true
URI = "CHANGE_ME"
APIKey = "CHANGE_ME"
ReSearch = true
importMode = "Move"
RssSyncTimer = 10
RefreshDownloadsTimer = 1
category = "radarr-4k"

[Sonarr-Anime]
Managed = true
URI = "CHANGE_ME"
APIKey = "CHANGE_ME"
ReSearch = true
importMode = "Move"
RssSyncTimer = 10
RefreshDownloadsTimer = 1
category = "sonarr-anime"

[Sonarr-TV]
Managed = true
URI = "CHANGE_ME"
APIKey = "CHANGE_ME"
ReSearch = true
importMode = "Move"
RssSyncTimer = 10
RefreshDownloadsTimer = 1
category = "sonarr-tv"

[QBit]
Host = "localhost"
Port = "8105"

[Settings]
ConsoleLevel = "INFO"
CompletedDownloadFolder = "CHANGE_ME"
NoInternetSleepTimer = 15
LoopSleepTimer = 5
FailedCategory = "failed"
RecheckCategory = "recheck"
IgnoreTorrentsYoungerThan = 180
FFprobeAutoUpdate = true
PingURLS = [ "one.one.one.one", "dns.google",]

[Radarr-1080p.Torrent]
AutoDelete = true
CaseSensitiveMatches = false
DoNotRemoveSlow = false
IgnoreTorrentsYoungerThan = 180
MaximumETA = 18000
MaximumDeletablePercentage = 0.99
FolderExclusionRegex = [ "\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b",]
FileNameExclusionRegex = [ "\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com",]
FileExtensionAllowlist = [ ".mp4", ".mkv", ".sub", ".ass", ".srt", ".!qB", ".parts",]

[Radarr-1080p.EntrySearch]
SearchMissing = false
PrioritizeTodaysReleases = true
AlsoSearchSpecials = false
SearchLimit = 5
DatabaseFile = "CHANGE_ME/sonarr.db"
SearchByYear = true
StartYear = 2021
LastYear = 1990
SearchInReverse = false
DoUpgradeSearch = false
QualityUnmetSearch = false
SearchRequestsEvery = 1800
SearchBySeries = true

[Radarr-4k.Torrent]
AutoDelete = true
CaseSensitiveMatches = false
DoNotRemoveSlow = false
IgnoreTorrentsYoungerThan = 180
MaximumETA = 18000
MaximumDeletablePercentage = 0.99
FolderExclusionRegex = [ "\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b",]
FileNameExclusionRegex = [ "\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com",]
FileExtensionAllowlist = [ ".mp4", ".mkv", ".sub", ".ass", ".srt", ".!qB", ".parts",]

[Radarr-4k.EntrySearch]
SearchMissing = false
PrioritizeTodaysReleases = true
AlsoSearchSpecials = false
SearchLimit = 5
DatabaseFile = "CHANGE_ME/sonarr.db"
SearchByYear = true
StartYear = 2021
LastYear = 1990
SearchInReverse = false
DoUpgradeSearch = false
QualityUnmetSearch = false
SearchRequestsEvery = 1800
SearchBySeries = true

[Sonarr-Anime.Torrent]
AutoDelete = true
CaseSensitiveMatches = false
DoNotRemoveSlow = false
IgnoreTorrentsYoungerThan = 180
MaximumETA = 18000
MaximumDeletablePercentage = 0.99
FolderExclusionRegex = [ "\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b",]
FileNameExclusionRegex = [ "\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com",]
FileExtensionAllowlist = [ ".mp4", ".mkv", ".sub", ".ass", ".srt", ".!qB", ".parts",]

[Sonarr-Anime.EntrySearch]
SearchMissing = false
PrioritizeTodaysReleases = true
AlsoSearchSpecials = false
SearchLimit = 5
DatabaseFile = "CHANGE_ME/sonarr.db"
SearchByYear = true
StartYear = 2021
LastYear = 1990
SearchInReverse = false
DoUpgradeSearch = false
QualityUnmetSearch = false
SearchRequestsEvery = 1800
SearchBySeries = true

[Sonarr-TV.Torrent]
AutoDelete = true
CaseSensitiveMatches = false
DoNotRemoveSlow = false
IgnoreTorrentsYoungerThan = 180
MaximumETA = 18000
MaximumDeletablePercentage = 0.99
FolderExclusionRegex = [ "\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b",]
FileNameExclusionRegex = [ "\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com",]
FileExtensionAllowlist = [ ".mp4", ".mkv", ".sub", ".ass", ".srt", ".!qB", ".parts",]

[Sonarr-TV.EntrySearch]
SearchMissing = false
PrioritizeTodaysReleases = true
AlsoSearchSpecials = false
SearchLimit = 5
DatabaseFile = "CHANGE_ME/sonarr.db"
SearchByYear = true
StartYear = 2021
LastYear = 1990
SearchInReverse = false
DoUpgradeSearch = false
QualityUnmetSearch = false
SearchRequestsEvery = 1800
SearchBySeries = true

[Radarr-1080p.Torrent.SeedingMode]
Enabled = false
add_tags = [ "Seeding Allowed",]
[[Radarr-1080p.Torrent.SeedingMode.Trackers]]
Name = "Rarbg"
url = "udp://9.rarbg.com:2810/announce"
add_tags = [ "rarbg",]
SuperSeedMode = false

[[Radarr-1080p.Torrent.SeedingMode.Trackers]]
Name = "Nyaa"
url = "http://nyaa.tracker.wf:7777/announce"
add_tags = [ "anime", "Nyaa",]
SuperSeedMode = false

[Radarr-1080p.EntrySearch.Ombi]
SearchOmbiRequests = false
OmbiURI = "http://localhost:5000"
OmbiAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Radarr-1080p.EntrySearch.Overseerr]
SearchOverseerrRequests = false
OverseerrURI = "http://localhost:5000"
OverseerrAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Radarr-4k.Torrent.SeedingMode]
Enabled = false
add_tags = [ "Seeding Allowed",]
[[Radarr-4k.Torrent.SeedingMode.Trackers]]
Name = "Rarbg"
url = "udp://9.rarbg.com:2810/announce"
add_tags = [ "rarbg",]
SuperSeedMode = false

[[Radarr-4k.Torrent.SeedingMode.Trackers]]
Name = "Nyaa"
url = "http://nyaa.tracker.wf:7777/announce"
add_tags = [ "anime", "Nyaa",]
SuperSeedMode = false

[Radarr-4k.EntrySearch.Ombi]
SearchOmbiRequests = false
OmbiURI = "http://localhost:5000"
OmbiAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Radarr-4k.EntrySearch.Overseerr]
SearchOverseerrRequests = false
OverseerrURI = "http://localhost:5000"
OverseerrAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Sonarr-Anime.Torrent.SeedingMode]
Enabled = false
add_tags = [ "Seeding Allowed",]
[[Sonarr-Anime.Torrent.SeedingMode.Trackers]]
Name = "Rarbg"
url = "udp://9.rarbg.com:2810/announce"
add_tags = [ "rarbg",]
SuperSeedMode = false

[[Sonarr-Anime.Torrent.SeedingMode.Trackers]]
Name = "Nyaa"
url = "http://nyaa.tracker.wf:7777/announce"
add_tags = [ "anime", "Nyaa",]
SuperSeedMode = false

[Sonarr-Anime.EntrySearch.Ombi]
SearchOmbiRequests = false
OmbiURI = "http://localhost:5000"
OmbiAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Sonarr-Anime.EntrySearch.Overseerr]
SearchOverseerrRequests = false
OverseerrURI = "http://localhost:5000"
OverseerrAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Sonarr-TV.Torrent.SeedingMode]
Enabled = false
add_tags = [ "Seeding Allowed",]
[[Sonarr-TV.Torrent.SeedingMode.Trackers]]
Name = "Rarbg"
url = "udp://9.rarbg.com:2810/announce"
add_tags = [ "rarbg",]
SuperSeedMode = false

[[Sonarr-TV.Torrent.SeedingMode.Trackers]]
Name = "Nyaa"
url = "http://nyaa.tracker.wf:7777/announce"
add_tags = [ "anime", "Nyaa",]
SuperSeedMode = false

[Sonarr-TV.EntrySearch.Ombi]
SearchOmbiRequests = false
OmbiURI = "http://localhost:5000"
OmbiAPIKey = "CHANGE_ME"
ApprovedOnly = true

[Sonarr-TV.EntrySearch.Overseerr]
SearchOverseerrRequests = false
OverseerrURI = "http://localhost:5000"
OverseerrAPIKey = "CHANGE_ME"
ApprovedOnly = true
