[tool.isort]
profile = "black"
line_length = 99
py_version = 38
known_third_party=["colorama", "coloredlogs", "ffmpeg", "pathos", "peewee", "pyarr", "qbittorrentapi", "requests", "tomlkit"]
known_local_folder=["qBitrr"]

[tool.black]
line-length = 99
target-version = ['py38']


[tool.autopep8]
max_line_length = 99
ignore = "E712"
in-place = true
recursive = true
aggressive = 3
