name: Version Bump

on:
  push:
    branches:
    - master

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[patch]') || startsWith(github.event.head_commit.message, '[minor]') || startsWith(github.event.head_commit.message, '[major]') }}
    env:
      RELEASE_TYPE: ${{ startsWith(github.event.head_commit.message, '[patch]') && 'patch' || startsWith(github.event.head_commit.message, '[minor]') && 'minor' || startsWith(github.event.head_commit.message, '[major]') && 'major' }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine
        pip install -r requirements.txt
    - name: Retrieve current version
      run: |
        echo "Current version: $(python setup.py --version)"
        echo "::set-output name=VERSION::$(python setup.py --version)"
      id: current_version
    - name: Bump Patch Version
      run: |
        bump2version --current-version $(python setup.py --version) ${{ env.RELEASE_TYPE }}
    - name: Retrieve new version
      run: |
        echo "::set-output name=VERSION::$(python setup.py --version)"
      id: new_version
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
      id: import_gpg
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: '[auto-release][${{ env.RELEASE_TYPE }}] Automated version bump: ${{ steps.current_version.outputs.VERSION }} >> ${{ steps.new_version.outputs.VERSION }}'
        tagging_message: v${{ steps.new_version.outputs.VERSION }}
        commit_options: -S
        commit_user_name: ${{ steps.import_gpg.outputs.name }}
        commit_user_email: ${{ steps.import_gpg.outputs.email }}
        commit_author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
