name: Generate Change Logs

on:
  push:
    branches:
    - master

jobs:
  change_logs:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[auto-changelogs]') }}
    env:
      RELEASE_TYPE: ${{ contains(github.event.head_commit.message, '[patch]') && 'patch' || contains(github.event.head_commit.message, '[minor]') && 'minor' ||contains(github.event.head_commit.message, '[major]') && 'major' }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install github-release-notes -g
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine
    - name: Retrieve current version
      run: |
        echo "::set-output name=VERSION::$(python setup.py --version)"
      id: current_version
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
      id: import_gpg
    - name: Change logs
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        gren changelog --override
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: '[auto-release] Generate changelogs for ${{ steps.current_version.outputs.VERSION }}'
        commit_options: -S
        commit_user_name: ${{ steps.import_gpg.outputs.name }}
        commit_user_email: ${{ steps.import_gpg.outputs.email }}
        commit_author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
