name: Generate Change Logs

on:
  release:
    types:
    - published

jobs:
  change_logs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0
        ref: master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install github-release-notes -g
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Retrieve current version
      run: |
        echo "Current version: $(python setup.py --version)"
        echo "::set-output name=VERSION::$(python setup.py --version)"
      id: current_version
    - name: Get git hash
      run: |
        echo "Current Hash: $(git rev-parse --short HEAD)"
        echo "::set-output name=HASH::$(git rev-parse --short HEAD)"
      id: git_hash
    - name: Update git hash
      run: |
        sed -i -e 's/git_hash = \".*\"/git_hash = \"${{ steps.git_hash.HASH }}\"/g' ./qBitrr/bundled_data.py
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
      id: import_gpg
    - name: Change logs
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        gren changelog --override
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: '[auto-publish] Generate changelogs for ${{ steps.current_version.outputs.VERSION }}'
        commit_options: -S
        commit_user_name: ${{ steps.import_gpg.outputs.name }}
        commit_user_email: ${{ steps.import_gpg.outputs.email }}
        commit_author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
