name: Publish to PyPi

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[auto-publish]') }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install github-release-notes -g
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
        pip install -r requirements.txt
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Release Notes
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        gren release --override
