name: Version Bump and deploy

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[deploy]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version setuptools wheel twine
      - name: Bump Patch Version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump2version --current-version $(python setup.py --version) patch setup.py
      - name: Commit version change to master - Push
        # Skip CI tag is import below otherwise it would trigger continous version bumps
        run: |
          git commit -am "[deploy] Automated version bump"
          git push
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    - name: Build package
      run: python -m build
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
