name: Create a Release

on:
  push:
    branches:
    - master

jobs:
  change_logs:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[auto-release]') }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install github-release-notes -g
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine
    - name: Retrieve current version
      run: |
        echo "::set-output name=VERSION::$(python setup.py --version)"
      id: current_version
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
      id: import_gpg
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: v${{ steps.current_version.outputs.VERSION }}
        title: v${{ steps.current_version.outputs.VERSION }}
    - name: Release Notes
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        gren release --override
